# Logging settings
hydra:
  run:
    dir: ./
  sweep:
    dir: ${log_dir}/${experiment}/sweep/${now:%Y-%m-%d_%H%M%S}
    subdir: ${hydra.job.num}

wandb: True
log_dir: logs
experiment: 3DVTAMP
wandb_group: experimental
resume_id: null
seed: 0

env: table_bussing
exp_name: table_bussing_sim
demo_folder: assets/data

# Data loader settings
weights_folder: assets/weights
dataset_root: assets/data/table_bussing_obj_suggester/sim
object_ids: [2, 3, 4, 5]

batch_size: 16
num_workers: 63

# Trainer settings
checkpoint_dir: checkpoints
max_epochs: 1000
ckpt_save_freq: 100
check_val_every_n_epoch: 10
accelerator: gpu
devices: 1

latent_dim: 1024
classifier: True
learning_rate: 0.001
